version: '3.8'

services:
  api-gymApp-pg:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=XAg8ns
      - POSTGRESQL_DATABASE=api_gymApp